REGIONS = {
    "eu": [
        'AX', 'DK', 'EE', 'FO', 'FI', 'GG', 'IS', 'IE', 'JE',
        'IM', 'LV', 'LT', 'NO', 'SJ', 'SE', 'GB', 'AL',
        'AD', 'BA', 'HR', 'CY', 'GI', 'GR', 'IT', 'MK',
        'VA', 'MT', 'ME', 'PT', 'SM', 'RS', 'SI', 'ES',
        'BY', 'BG', 'CZ', 'GE', 'HU', 'MD', 'PL', 'RO',
        'RU', 'SK', 'UA', 'AT', 'BE', 'FR', 'DE', 'LI',
        'LU', 'MC', 'NL', 'CH', 'AU', 'NF', 'NZ', 'BW',
        'LS', 'NA', 'ZA', 'SZ',
    ],
    "na": [
        'BM', 'CA', 'GL', 'MX', 'PM', 'US', 'AR',
        'BO', 'BR', 'CL', 'CO', 'EC', 'FK', 'GF',
        'GY', 'PY', 'PE', 'SR', 'UY', 'VE'
    ],
    "jp": ["JP"],
    "hk": ["HK"],
    # "jp": ["CN", "HK", "JP", "KP", "KR", "MO", "MN", "TW"],
}

COUNTRY_REGION = {
    "AX": "eu",
    "DK": "eu",
    "EE": "eu",
    "FO": "eu",
    "FI": "eu",
    "GG": "eu",
    "IS": "eu",
    "IE": "eu",
    "JE": "eu",
    "IM": "eu",
    "LV": "eu",
    "LT": "eu",
    "NO": "eu",
    "SJ": "eu",
    "SE": "eu",
    "GB": "eu",
    "AL": "eu",
    "AD": "eu",
    "BA": "eu",
    "HR": "eu",
    "CY": "eu",
    "GI": "eu",
    "GR": "eu",
    "IT": "eu",
    "MK": "eu",
    "VA": "eu",
    "MT": "eu",
    "ME": "eu",
    "PT": "eu",
    "SM": "eu",
    "RS": "eu",
    "SI": "eu",
    "ES": "eu",
    "BY": "eu",
    "BG": "eu",
    "CZ": "eu",
    "GE": "eu",
    "HU": "eu",
    "MD": "eu",
    "PL": "eu",
    "RO": "eu",
    "RU": "eu",
    "SK": "eu",
    "UA": "eu",
    "AT": "eu",
    "BE": "eu",
    "FR": "eu",
    "DE": "eu",
    "LI": "eu",
    "LU": "eu",
    "MC": "eu",
    "NL": "eu",
    "CH": "eu",
    "AU": "eu",
    "NF": "eu",
    "NZ": "eu",
    "BW": "eu",
    "LS": "eu",
    "NA": "eu",
    "ZA": "eu",
    "SZ": "eu",
    "BM": "na",
    "CA": "na",
    "GL": "na",
    "MX": "na",
    "PM": "na",
    "US": "na",
    "AR": "na",
    "BO": "na",
    "BR": "na",
    "CL": "na",
    "CO": "na",
    "EC": "na",
    "FK": "na",
    "GF": "na",
    "GY": "na",
    "PY": "na",
    "PE": "na",
    "SR": "na",
    "UY": "na",
    "VE": "na",
    # "CN": "asia",
    "HK": "hk",
    "JP": "jp",
    # "KP": "asia",
    # "KR": "asia",
    # "MO": "asia",
    # "MN": "asia",
    # "TW": "asia",
}
